### ISSUE TITLE
MiniGPT-4 flaws with captions

### ISSUE THREAD

**Issue by pipinstallyp** [pipinstallyp/minigpt4-batch#1]
If you want the captions to have more or less of something, based on your observation. Please drop your suggestions below.

**Comment by charkgan** [comment]
remove the starting phrase "This image shows"

**Comment by rafstahelin** [comment]
would be awesome to add a feature to automatically add the each dataset folder name to the image caption

**Comment by rafstahelin** [comment]
another feature that would be great is saving captions to the same folder as the images being captioned

**Comment by gessyoo** [comment]
I'd like a repetition-penalty to be added as an option.  Maybe a function to stop generating when the words in the caption begin to repeat,  e.g. 
`def remove_duplicates(string):
    words = string.split(', ')  # Split the string into individual words
    unique_words = []
    for word in words:
        if word not in unique_words:
            unique_words.append(word)
        else:
            break  # Stop appending words once a duplicate is found
    return ', '.join(unique_words)
`

**Comment by rafstahelin** [comment]
How's flavors coming along?

**Comment by charkgan** [comment]
1. exclude the keyword "_caption" from the caption txt file
2. own prompt
3. ending the loop after completion
4. adding input dir argument
5. adding output dir argument

**Comment by gessyoo** [comment]
> remove the starting phrase "This image shows"

I've made a fork with some additional features, including removing  "The image shows" and "The image is,"  etc. and the _caption extension from the text captions.

**Comment by pipinstallyp** [comment]
@gessyoo great code and tweaks! Added your repo in the footnotes of my README

**Comment by DarkAlchy** [comment]
> @gessyoo great code and tweaks! Added your repo in the footnotes of my README

He doesn't even allow issues to be posted, and I have one that yours did not have.

Traceback (most recent call last):
  File "D:\minigpt4-batch-tweaked\app.py", line 206, in <module>
    caption = describe_image(image_path, chat, chat_state, img_list, num_beams, temperature, repetition_penalty, min_sentence_length=8, max_sentence_length=35)
  File "D:\minigpt4-batch-tweaked\app.py", line 107, in describe_image
    generated_caption = generated_caption.replace("The woman", args.name).replace("the woman", args.name).replace("a woman", args.name).replace("woman", args.name)  # Substitute the name
TypeError: replace() argument 2 must be str, not None
